# -*- coding: utf-8 -*-
"""v1.25.0 批量补丁 _d：ui_settings.py 的「标签优化」页 + 反馈 2 的间距修复。

「标签优化」整页作为新方法追加到 SettingsDialog 类尾（缩进仍是类内 4 空格）——
用「文件末尾三行」当锚点比插在中间安全得多：中间插入一旦锚点撞上重复片段，
后面的方法会整块错位。
"""
import os

ROOT = r"Z:/【01】自研软件/【26-19】本地影视中心"
SRC = os.path.join(ROOT, "src")
REPORT = []


def read(rel):
    with open(os.path.join(SRC, rel), encoding="utf-8") as f:
        return f.read()


def write(rel, text):
    with open(os.path.join(SRC, rel), "w", encoding="utf-8", newline="") as f:
        f.write(text)


def patch(rel, label, old, new, count=1):
    s = read(rel)
    n = s.count(old)
    if n != count:
        raise SystemExit(f"✗ [{rel} :: {label}] 锚点命中 {n} 次，期望 {count} 次\n"
                         f"----- 锚点 -----\n{old[:500]}\n----------------")
    write(rel, s.replace(old, new))
    REPORT.append(f"OK  {rel}  {label}")


R = "ui_settings.py"

# ===========================================================================
# 反馈 2：数据导出 / 导入 页，勾选区与下方按钮行贴在一起
# ===========================================================================
patch(R, "反馈 2：导出组内间距统一为 10",
      '        g1 = QGroupBox("数据导出 / 导入")\n'
      '        g1v = QVBoxLayout(g1)\n'
      '        h1 = QLabel(rich(\n',
      '        g1 = QGroupBox("数据导出 / 导入")\n'
      '        g1v = QVBoxLayout(g1)\n'
      '        # v1.25.0（反馈 2）：这里原来是 Qt 默认行距，而下面那个勾选区用了\n'
      '        # ph.setSpacing(2) —— 三列勾选框与「全选 / 全不选 / 只选轻量项」按钮行\n'
      '        # 挤在一起（截图为证）。把两处间距统一成 10，上下都拉开。\n'
      '        g1v.setSpacing(10)\n'
      '        h1 = QLabel(rich(\n')

patch(R, "反馈 2：勾选区行距 2 -> 10",
      '        ph.setSpacing(2)\n',
      '        ph.setSpacing(10)      # v1.25.0（反馈 2）：原为 2，与下方按钮行贴着\n')

# ===========================================================================
# 反馈 4：标签优化整页
# ===========================================================================
patch(R, "反馈 4：追加标签优化页与处理函数",
      '        self.s.remove_library(lib["name"])\n'
      '        self._rebuild_lib_list()\n'
      '        if self.on_changed:\n'
      '            self.on_changed()\n',
      '        self.s.remove_library(lib["name"])\n'
      '        self._rebuild_lib_list()\n'
      '        if self.on_changed:\n'
      '            self.on_changed()\n'
      '\n'
      '    # ==================================================================\n'
      '    # 标签优化（v1.25.0 反馈 4）\n'
      '    # ------------------------------------------------------------------\n'
      '    # 与「智能推荐」同源：都用「普通智能算法 / AI 智能算法」那套本地离线能力，\n'
      '    # 区别在**打分对象**是标签本身 —— 结合标题与 nfo 里已有的信息，给 nfo 的\n'
      '    # <genre> 补全、并做日语→中文这类标签转化。\n'
      '    # 流程刻意拆成两段：\n'
      '    #   1) 「扫描并预览」= 只读盘 + 只算，把每个文件会变成什么样列出来；\n'
      '    #   2) 「执行写入」= 用户看过预览、点过确认之后才落盘（可选自动备份）。\n'
      '    # 这样即使算法给出一堆怪标签，也不会在用户没看见的情况下改掉 5 万个 nfo。\n'
      '    # ==================================================================\n'
      '    def _build_tagopt(self):\n'
      '        page = QWidget()\n'
      '        v = QVBoxLayout(page)\n'
      '        v.setContentsMargins(18, 16, 18, 16)\n'
      '        v.setSpacing(12)\n'
      '        to = self.s.tagopt\n'
      '\n'
      '        # ---------- 处理范围 ----------\n'
      '        g1 = QGroupBox("处理范围")\n'
      '        g1v = QVBoxLayout(g1)\n'
      '        h1 = QLabel(rich(\n'
      '            "按范围找出其中**已经刮削好的 .nfo**，结合**标题**与 nfo 里已有的信息"\n'
      '            "（片商 / 系列 / 原有标签）推断标签，先给一份**预览**，确认后才写回磁盘。\\n"\n'
      '            "· 普通智能算法：纯本地规则 —— 标题关键词 + 片商 / 系列伪标签 + 全库标签共现；\\n"\n'
      '            "· AI 智能算法：在普通算法之上叠加**本地离线 AI**（Ollama 不可用时自动降级）。"))\n'
      '        h1.setWordWrap(True)\n'
      '        h1.setStyleSheet("color:#a2967f;font-size:11px;")\n'
      '        g1v.addWidget(h1)\n'
      '\n'
      '        srow = QHBoxLayout()\n'
      '        srow.setSpacing(14)\n'
      '        self.rb_to_file = QRadioButton("单一文件")\n'
      '        self.rb_to_folder = QRadioButton("文件夹")\n'
      '        self.rb_to_lib = QRadioButton("媒体库")\n'
      '        for rb in (self.rb_to_file, self.rb_to_folder, self.rb_to_lib):\n'
      '            srow.addWidget(rb)\n'
      '        srow.addStretch(1)\n'
      '        g1v.addLayout(srow)\n'
      '\n'
      '        prow = QHBoxLayout()\n'
      '        prow.setSpacing(8)\n'
      '        prow.addWidget(QLabel("路径"))\n'
      '        self.to_path = QLineEdit()\n'
      '        self.to_path.setText(str(to.get("path") or ""))\n'
      '        self.to_path.setPlaceholderText("视频文件或 .nfo 的完整路径")\n'
      '        prow.addWidget(self.to_path, 1)\n'
      '        self.btn_to_browse = QPushButton("浏览…")\n'
      '        self.btn_to_browse.setObjectName("Ghost")\n'
      '        self.btn_to_browse.clicked.connect(self._tagopt_browse)\n'
      '        prow.addWidget(self.btn_to_browse)\n'
      '        g1v.addLayout(prow)\n'
      '\n'
      '        lrow = QHBoxLayout()\n'
      '        lrow.setSpacing(8)\n'
      '        lrow.addWidget(QLabel("媒体库"))\n'
      '        self.to_lib = QComboBox()\n'
      '        self.to_lib.setMinimumWidth(260)\n'
      '        for lib in (self.s.libraries or []):\n'
      '            nm = lib.get("name") or ""\n'
      '            if nm:\n'
      '                self.to_lib.addItem(nm, nm)\n'
      '        want_lib = str(to.get("library") or "")\n'
      '        if want_lib:\n'
      '            idx = self.to_lib.findData(want_lib)\n'
      '            if idx >= 0:\n'
      '                self.to_lib.setCurrentIndex(idx)\n'
      '        lrow.addWidget(self.to_lib)\n'
      '        self.lb_to_scope = QLabel("—")\n'
      '        self.lb_to_scope.setStyleSheet("color:#8c8071;font-size:11px;")\n'
      '        self.lb_to_scope.setWordWrap(True)\n'
      '        lrow.addWidget(self.lb_to_scope, 1)\n'
      '        g1v.addLayout(lrow)\n'
      '\n'
      '        sc = str(to.get("scope") or "file")\n'
      '        (self.rb_to_folder if sc == "folder" else\n'
      '         self.rb_to_lib if sc == "library" else self.rb_to_file).setChecked(True)\n'
      '        v.addWidget(g1)\n'
      '\n'
      '        # ---------- 优化方式 ----------\n'
      '        g2 = QGroupBox("优化方式")\n'
      '        g2v = QVBoxLayout(g2)\n'
      '        self.rb_to_normal = QRadioButton("普通智能算法（本地规则 + 全库标签共现）")\n'
      '        self.rb_to_ai = QRadioButton("AI 智能算法（本地离线 AI 辅助补全）")\n'
      '        (self.rb_to_ai if to.get("algo") == "ai"\n'
      '         else self.rb_to_normal).setChecked(True)\n'
      '        g2v.addWidget(self.rb_to_normal)\n'
      '        g2v.addWidget(self.rb_to_ai)\n'
      '        self.to_ai_state = QLabel("点上面的「AI 智能算法」会检测本机 Ollama 是否可用；"\n'
      '                                  "用哪个模型跟「智能推荐」页共用同一项设置。")\n'
      '        self.to_ai_state.setWordWrap(True)\n'
      '        self.to_ai_state.setStyleSheet("color:#8c8071;font-size:11px;")\n'
      '        g2v.addWidget(self.to_ai_state)\n'
      '\n'
      '        self.ck_to_trans = QCheckBox("日语标签转中文（例：中出し → 中出）")\n'
      '        self.ck_to_over = QCheckBox("用中文覆盖原日语标签（不勾 = 保留原日语，另补一条中文）")\n'
      '        self.ck_to_full = QCheckBox("补全缺失标签（标题关键词 / 片商 / 系列 / 全库共现）")\n'
      '        self.ck_to_bak = QCheckBox("写入前备份原 nfo（*.nfo.bak-<时间戳>）")\n'
      '        for ck, key, dflt in ((self.ck_to_trans, "translate", True),\n'
      '                              (self.ck_to_over, "overwrite", False),\n'
      '                              (self.ck_to_full, "complete", True),\n'
      '                              (self.ck_to_bak, "backup", True)):\n'
      '            ck.setChecked(bool(to.get(key, dflt)))\n'
      '            g2v.addWidget(ck)\n'
      '        v.addWidget(g2)\n'
      '\n'
      '        # ---------- 预览与执行 ----------\n'
      '        g3 = QGroupBox("预览与执行（先预览，确认后才写盘）")\n'
      '        g3v = QVBoxLayout(g3)\n'
      '        arow = QHBoxLayout()\n'
      '        arow.setSpacing(8)\n'
      '        self.btn_to_scan = QPushButton("扫描并预览")\n'
      '        self.btn_to_scan.setObjectName("Primary")\n'
      '        self.btn_to_scan.setToolTip("只读盘 + 只算，不改动任何文件")\n'
      '        self.btn_to_scan.clicked.connect(self._tagopt_scan)\n'
      '        arow.addWidget(self.btn_to_scan)\n'
      '        self.btn_to_run = QPushButton("执行写入")\n'
      '        self.btn_to_run.setObjectName("Ghost")\n'
      '        self.btn_to_run.setEnabled(False)\n'
      '        self.btn_to_run.setToolTip("把预览结果写回 nfo（会先弹一次确认）")\n'
      '        self.btn_to_run.clicked.connect(self._tagopt_apply)\n'
      '        arow.addWidget(self.btn_to_run)\n'
      '        self.btn_to_clear = QPushButton("清空预览")\n'
      '        self.btn_to_clear.setObjectName("Ghost")\n'
      '        self.btn_to_clear.clicked.connect(self._tagopt_clear)\n'
      '        arow.addWidget(self.btn_to_clear)\n'
      '        arow.addStretch(1)\n'
      '        g3v.addLayout(arow)\n'
      '\n'
      '        self.to_progress = QProgressBar()\n'
      '        self.to_progress.setRange(0, 100)\n'
      '        self.to_progress.setValue(0)\n'
      '        self.to_progress.setTextVisible(False)\n'
      '        self.to_progress.setFixedHeight(10)\n'
      '        g3v.addWidget(self.to_progress)\n'
      '        self.to_status = QLabel("还没有扫描。选好范围后点「扫描并预览」——"\n'
      '                               "这一步只读不写，不会改动任何文件。")\n'
      '        self.to_status.setWordWrap(True)\n'
      '        # 进度文案里会出现 `||`、`&` 之类的原文，强制纯文本，别让 QLabel 当富文本解析\n'
      '        self.to_status.setTextFormat(Qt.PlainText)\n'
      '        self.to_status.setStyleSheet("color:#8c8071;font-size:11px;")\n'
      '        g3v.addWidget(self.to_status)\n'
      '\n'
      '        self.to_table = QTableWidget(0, 5)\n'
      '        self.to_table.setHorizontalHeaderLabels(\n'
      '            ["文件", "引擎", "原有标签", "将新增", "日语→中文"])\n'
      '        self.to_table.setEditTriggers(QAbstractItemView.NoEditTriggers)\n'
      '        self.to_table.verticalHeader().setVisible(False)\n'
      '        self.to_table.setShowGrid(False)\n'
      '        self.to_table.setMinimumHeight(230)\n'
      '        hh = self.to_table.horizontalHeader()\n'
      '        hh.setSectionResizeMode(0, QHeaderView.Stretch)\n'
      '        for _i in (1, 2, 3, 4):\n'
      '            hh.setSectionResizeMode(_i, QHeaderView.ResizeToContents)\n'
      '        g3v.addWidget(self.to_table, 1)\n'
      '        v.addWidget(g3)\n'
      '\n'
      '        v.addStretch(1)\n'
      '        self._to_plans = []\n'
      '        self._to_changed = []\n'
      '\n'
      '        # ---------- 统一接信号 ----------\n'
      '        # 放在最后接：上面 setChecked / setCurrentIndex 都发生在连接之前，\n'
      '        # 否则回调会读到「还没建出来」的控件（本项目踩过这种构造期回调）。\n'
      '        for rb in (self.rb_to_file, self.rb_to_folder, self.rb_to_lib):\n'
      '            rb.toggled.connect(self._tagopt_scope_changed)\n'
      '            rb.toggled.connect(self._tagopt_save_prefs)\n'
      '        for rb in (self.rb_to_normal, self.rb_to_ai):\n'
      '            rb.toggled.connect(self._on_tagopt_algo_changed)\n'
      '        for ck in (self.ck_to_trans, self.ck_to_over, self.ck_to_full, self.ck_to_bak):\n'
      '            ck.toggled.connect(self._tagopt_save_prefs)\n'
      '        self.ck_to_trans.toggled.connect(self._on_to_trans_changed)\n'
      '        self.to_path.editingFinished.connect(self._tagopt_save_prefs)\n'
      '        self.to_lib.currentIndexChanged.connect(self._tagopt_save_prefs)\n'
      '        self._tagopt_scope_changed()\n'
      '        self._on_to_trans_changed()\n'
      '        return page\n'
      '\n'
      '    # ---------- 标签优化：状态与偏好 ----------\n'
      '    def _tagopt_scope(self):\n'
      '        if self.rb_to_folder.isChecked():\n'
      '            return "folder"\n'
      '        if self.rb_to_lib.isChecked():\n'
      '            return "library"\n'
      '        return "file"\n'
      '\n'
      '    def _tagopt_value(self):\n'
      '        if self._tagopt_scope() == "library":\n'
      '            return str(self.to_lib.currentData() or "")\n'
      '        return str(self.to_path.text() or "").strip()\n'
      '\n'
      '    def _tagopt_kwargs(self):\n'
      '        """交给 tagopt.TagOptimizer.plan_one 的参数。"""\n'
      '        trans = self.ck_to_trans.isChecked()\n'
      '        return dict(algo=("ai" if self.rb_to_ai.isChecked() else "normal"),\n'
      '                    translate=trans,\n'
      '                    overwrite=trans and self.ck_to_over.isChecked(),\n'
      '                    complete=self.ck_to_full.isChecked(),\n'
      '                    use_cooccur=True,\n'
      '                    ai_model=(self.s.recommend.get("ai_model") or None),\n'
      '                    ai_limit=14)\n'
      '\n'
      '    def _tagopt_save_prefs(self, *_):\n'
      '        self.s.set_tagopt(scope=self._tagopt_scope(),\n'
      '                          path=str(self.to_path.text() or "").strip(),\n'
      '                          library=str(self.to_lib.currentData() or ""),\n'
      '                          algo=("ai" if self.rb_to_ai.isChecked() else "normal"),\n'
      '                          translate=self.ck_to_trans.isChecked(),\n'
      '                          overwrite=self.ck_to_over.isChecked(),\n'
      '                          complete=self.ck_to_full.isChecked(),\n'
      '                          backup=self.ck_to_bak.isChecked())\n'
      '\n'
      '    def _tagopt_scope_changed(self, *_):\n'
      '        sc = self._tagopt_scope()\n'
      '        is_lib = (sc == "library")\n'
      '        self.to_path.setEnabled(not is_lib)\n'
      '        self.btn_to_browse.setEnabled(not is_lib)\n'
      '        self.to_lib.setEnabled(is_lib)\n'
      '        if sc == "file":\n'
      '            self.to_path.setPlaceholderText("视频文件或 .nfo 的完整路径")\n'
      '            self.btn_to_browse.setText("选文件…")\n'
      '            tip = "只处理这一个文件对应的 nfo"\n'
      '            place = "视频文件或 .nfo 的完整路径"\n'
      '        elif sc == "folder":\n'
      '            self.to_path.setPlaceholderText("文件夹路径（其下所有 .nfo 都会被处理）")\n'
      '            self.btn_to_browse.setText("选文件夹…")\n'
      '            tip = "会递归处理该目录下找到的全部 .nfo（*.bak-* 备份文件会被跳过）"\n'
      '            place = "文件夹路径（其下所有 .nfo 都会被处理）"\n'
      '        else:\n'
      '            self.to_path.setPlaceholderText("（媒体库模式下不用填路径）")\n'
      '            self.btn_to_browse.setText("浏览…")\n'
      '            tip = ("当前共 %d 个媒体库" % len(self.s.libraries or []))\n'
      '            place = "（媒体库模式下不用填路径）"\n'
      '        self.to_path.setPlaceholderText(place)\n'
      '        self.lb_to_scope.setText(tip)\n'
      '\n'
      '    def _on_to_trans_changed(self, *_):\n'
      '        """「覆盖源标签」只有先勾了「日语转中文」才有意义。"""\n'
      '        on = self.ck_to_trans.isChecked()\n'
      '        self.ck_to_over.setEnabled(on)\n'
      '        self.ck_to_over.setToolTip(\n'
      '            "勾上：日语标签直接被中文替换（标签总数不变）。\\n"\n'
      '            "不勾：保留原日语标签，并在它后面补一条中文（两种写法都能搜到）。"\n'
      '            if on else "先勾上「日语标签转中文」才用得到这一项。")\n'
      '\n'
      '    def _tagopt_browse(self):\n'
      '        cur = str(self.to_path.text() or "").strip()\n'
      '        if self._tagopt_scope() == "folder":\n'
      '            p = QFileDialog.getExistingDirectory(self, "选择文件夹", cur)\n'
      '        else:\n'
      '            p, _flt = QFileDialog.getOpenFileName(\n'
      '                self, "选择文件", cur,\n'
      '                "视频或 nfo (*.mp4 *.mkv *.avi *.wmv *.ts *.mov *.nfo);;所有文件 (*)")\n'
      '        if p:\n'
      '            self.to_path.setText(p)\n'
      '            self._tagopt_save_prefs()\n'
      '\n'
      '    def _on_tagopt_algo_changed(self, *_):\n'
      '        self._tagopt_save_prefs()\n'
      '        if not self.rb_to_ai.isChecked():\n'
      '            self.to_ai_state.setStyleSheet("color:#8c8071;font-size:11px;")\n'
      '            self.to_ai_state.setText("当前用普通智能算法：纯本地规则 + 全库标签共现，"\n'
      '                                     "完全不依赖 AI，速度最快。")\n'
      '            return\n'
      '        w = getattr(self, "_to_ai_worker", None)\n'
      '        if w is not None and w.isRunning():\n'
      '            return\n'
      '        self.to_ai_state.setStyleSheet("color:#e8d27a;font-size:11px;")\n'
      '        self.to_ai_state.setText("正在检测本地 AI 引擎…")\n'
      '        self._to_ai_worker = AiProbeWorker()\n'
      '        self._to_ai_worker.done.connect(self._on_to_ai_probe)\n'
      '        self._to_ai_worker.start()\n'
      '\n'
      '    def _on_to_ai_probe(self, st):\n'
      '        st = st or {}\n'
      '        eng = st.get("engine")\n'
      '        if eng == "ollama":\n'
      '            self.to_ai_state.setStyleSheet("color:#9ecf8a;font-size:11px;")\n'
      '            self.to_ai_state.setText("本地离线 AI 可用：" + html_esc(st.get("label"))\n'
      '                                     + "　—— 想换模型去「智能推荐」页填。")\n'
      '        elif eng == "error":\n'
      '            self.to_ai_state.setStyleSheet("color:#e08a7a;font-size:11px;")\n'
      '            self.to_ai_state.setText("AI 引擎检测失败，将退回内置算法："\n'
      '                                     + html_esc(st.get("detail")))\n'
      '        else:\n'
      '            self.to_ai_state.setStyleSheet("color:#e8d27a;font-size:11px;")\n'
      '            self.to_ai_state.setText("没检测到可用的本地模型，将退回内置算法："\n'
      '                                     + html_esc(st.get("detail")))\n'
      '\n'
      '    # ---------- 标签优化：执行 ----------\n'
      '    def _tagopt_clear(self):\n'
      '        self._to_plans = []\n'
      '        self._to_changed = []\n'
      '        self.to_table.setRowCount(0)\n'
      '        self.btn_to_run.setEnabled(False)\n'
      '        self.to_progress.setValue(0)\n'
      '        self.to_status.setStyleSheet("color:#8c8071;font-size:11px;")\n'
      '        self.to_status.setText("已清空预览。")\n'
      '\n'
      '    def _on_to_progress(self, i, n, msg):\n'
      '        if n and n > 0:\n'
      '            self.to_progress.setValue(max(0, min(100, int(round(i * 100.0 / n)))))\n'
      '        if msg:\n'
      '            self.to_status.setText(str(msg))\n'
      '\n'
      '    def _tagopt_scan(self):\n'
      '        w = getattr(self, "_to_scan_worker", None)\n'
      '        if w is not None and w.isRunning():\n'
      '            return\n'
      '        sc = self._tagopt_scope()\n'
      '        val = self._tagopt_value()\n'
      '        if not val:\n'
      '            self.to_status.setStyleSheet("color:#e08a7a;font-size:11px;")\n'
      '            self.to_status.setText(\n'
      '                "✗ 还没有可处理的目标 —— 先填路径（或选一个媒体库）。"\n'
      '                if sc != "library" else\n'
      '                "✗ 当前没有任何媒体库 —— 先去「服务管理」建一个。")\n'
      '            return\n'
      '        self._tagopt_save_prefs()\n'
      '        self.btn_to_scan.setEnabled(False)\n'
      '        self.btn_to_run.setEnabled(False)\n'
      '        self.to_table.setRowCount(0)\n'
      '        self.to_progress.setValue(0)\n'
      '        self.to_status.setStyleSheet("color:#e8d27a;font-size:11px;")\n'
      '        self.to_status.setText("正在扫描 " + val + " …这一步只读不写。")\n'
      '        opt = tagopt_mod.TagOptimizer(self.s)\n'
      '        self._to_scan_worker = TagOptScanWorker(opt, sc, val, self._tagopt_kwargs())\n'
      '        self._to_scan_worker.progress.connect(self._on_to_progress)\n'
      '        self._to_scan_worker.done.connect(self._on_tagopt_scan)\n'
      '        self._to_scan_worker.start()\n'
      '\n'
      '    def _on_tagopt_scan(self, plans, err):\n'
      '        self.btn_to_scan.setEnabled(True)\n'
      '        self.to_progress.setValue(0)\n'
      '        plans = list(plans or [])\n'
      '        self._to_plans = plans\n'
      '        if err:\n'
      '            self._to_changed = []\n'
      '            self.to_table.setRowCount(0)\n'
      '            self.btn_to_run.setEnabled(False)\n'
      '            self.to_status.setStyleSheet("color:#e08a7a;font-size:11px;")\n'
      '            self.to_status.setText("✗ " + str(err))\n'
      '            return\n'
      '        changed = [p for p in plans if not p.get("error")\n'
      '                   and list(p.get("before") or []) != list(p.get("after") or [])]\n'
      '        self._to_changed = changed\n'
      '        self._fill_to_table(changed)\n'
      '        self.btn_to_run.setEnabled(bool(changed))\n'
      '        if not changed:\n'
      '            self.to_status.setStyleSheet("color:#9ecf8a;font-size:11px;")\n'
      '            self.to_status.setText(\n'
      '                "✓ 扫了 %d 个 nfo，标签都已经是最新的，没有需要改的。" % len(plans))\n'
      '            return\n'
      '        add_n = sum(len(p.get("added") or []) for p in changed)\n'
      '        tr_n = sum(len(p.get("translated") or []) for p in changed)\n'
      '        ai_n = sum(1 for p in changed if p.get("engine") == "ollama")\n'
      '        bad_n = sum(1 for p in plans if p.get("error"))\n'
      '        bits = ["扫了 %d 个 nfo，其中 %d 个标签会变化；预计新增 %d 条标签"\n'
      '                % (len(plans), len(changed), add_n)]\n'
      '        if tr_n:\n'
      '            bits.append("、翻译 %d 条日语标签" % tr_n)\n'
      '        if ai_n:\n'
      '            bits.append("（%d 个用了本地离线 AI）" % ai_n)\n'
      '        if bad_n:\n'
      '            bits.append("；另有 %d 个读取失败" % bad_n)\n'
      '        bits.append("。确认无误后点「执行写入」。表格里的数字都能悬停看明细。")\n'
      '        self.to_status.setStyleSheet("color:#e8d27a;font-size:11px;")\n'
      '        self.to_status.setText("".join(bits))\n'
      '\n'
      '    def _fill_to_table(self, plans, cap=800):\n'
      '        self.to_table.setRowCount(0)\n'
      '        for p in list(plans or [])[:cap]:\n'
      '            r = self.to_table.rowCount()\n'
      '            self.to_table.insertRow(r)\n'
      '            nfo = str(p.get("nfo") or "")\n'
      '            it0 = QTableWidgetItem(os.path.basename(nfo) or nfo)\n'
      '            it0.setToolTip(nfo)\n'
      '            self.to_table.setItem(r, 0, it0)\n'
      '            self.to_table.setItem(r, 1, QTableWidgetItem(\n'
      '                "本地 AI（Ollama）" if p.get("engine") == "ollama" else "内置算法"))\n'
      '            self.to_table.setItem(r, 2, QTableWidgetItem(str(len(p.get("before") or []))))\n'
      '            added = [str(x) for x in (p.get("added") or [])]\n'
      '            it3 = QTableWidgetItem("+" + str(len(added)))\n'
      '            it3.setToolTip("、".join(added) if added else "（无新增）")\n'
      '            self.to_table.setItem(r, 3, it3)\n'
      '            tr = list(p.get("translated") or [])\n'
      '            it4 = QTableWidgetItem(str(len(tr)))\n'
      '            it4.setToolTip("；".join("%s → %s" % (a, b) for a, b in tr) if tr\n'
      '                           else "（没有需要翻译的日语标签）")\n'
      '            self.to_table.setItem(r, 4, it4)\n'
      '        n = len(plans or [])\n'
      '        if n > cap:\n'
      '            self.to_status.setText(self.to_status.text()\n'
      '                                   + "（表格只列前 %d 个，实际会处理全部 %d 个）" % (cap, n))\n'
      '\n'
      '    def _tagopt_apply(self):\n'
      '        w = getattr(self, "_to_run_worker", None)\n'
      '        if w is not None and w.isRunning():\n'
      '            return\n'
      '        changed = list(self._to_changed or [])\n'
      '        if not changed:\n'
      '            return\n'
      '        n = len(changed)\n'
      '        backup = self.ck_to_bak.isChecked()\n'
      '        if backup:\n'
      '            tail = "\\n\\n写入前会把每个原文件另存为 *.nfo.bak-<时间戳>，随时可手工还原。"\n'
      '        else:\n'
      '            tail = "\\n\\n注意：你已经关掉「写入前备份」——原标签会被直接改写，无法撤销。"\n'
      '        if QMessageBox.question(\n'
      '                self, "确认写入标签",\n'
      '                "将把预览结果写回 %d 个 nfo 文件。" % n + tail,\n'
      '                QMessageBox.Yes | QMessageBox.No, QMessageBox.No) != QMessageBox.Yes:\n'
      '            return\n'
      '        self.btn_to_run.setEnabled(False)\n'
      '        self.btn_to_scan.setEnabled(False)\n'
      '        self.to_progress.setValue(0)\n'
      '        self.to_status.setStyleSheet("color:#e8d27a;font-size:11px;")\n'
      '        self.to_status.setText("正在写入 %d 个 nfo…（同时同步数据库里的标签）" % n)\n'
      '        opt = tagopt_mod.TagOptimizer(self.s)\n'
      '        self._to_run_worker = TagOptRunWorker(opt, changed, backup)\n'
      '        self._to_run_worker.progress.connect(self._on_to_progress)\n'
      '        self._to_run_worker.done.connect(self._on_tagopt_applied)\n'
      '        self._to_run_worker.start()\n'
      '\n'
      '    def _on_tagopt_applied(self, stats):\n'
      '        self.btn_to_scan.setEnabled(True)\n'
      '        self.to_progress.setValue(0)\n'
      '        s = stats or {}\n'
      '        errs = list(s.get("errors") or [])\n'
      '        head = ("✓ 完成：写入 %d 个 · 跳过 %d 个 · 失败 %d 个 · 数据库同步 %d 条"\n'
      '                % (s.get("written", 0), s.get("skipped", 0),\n'
      '                   s.get("failed", 0), s.get("db_synced", 0)))\n'
      '        if errs:\n'
      '            head += "（首个错误：" + str(errs[0]) + "）"\n'
      '            self.to_status.setStyleSheet("color:#e8d27a;font-size:11px;")\n'
      '        else:\n'
      '            self.to_status.setStyleSheet("color:#9ecf8a;font-size:11px;")\n'
      '        self.to_status.setText(head)\n'
      '        applog.log("[标签优化] " + head)\n'
      '        self._to_plans = []\n'
      '        self._to_changed = []\n'
      '        self.btn_to_run.setEnabled(False)\n'
      '        if self.on_changed:\n'
      '            self.on_changed()\n')

print("\n".join(REPORT))
print(f"patch _d 完成：{len(REPORT)} 项")
